import {build} from 'esbuild';
const source=String.raw`import assert from 'node:assert/strict';import {replacementForMissingPortrait} from './services/avg/missingArtRecovery';
const npc={id:'n',性别:'男',年龄:40};const binding={npcId:'n',assetId:'old@1:V1',baseAssetId:'old@1:B1',characterKey:'tianlong:n',faceFamilyKey:'face:n'};
const base={id:'new@1:B1',image:'/base',gender:'男',ageRange:{min:30,max:60},portraitVerified:true,characterKey:'tianlong:n',faceFamilyKey:'face:n',profile:{}};
const variant={...base,id:'new@1:V1',baseAssetId:base.id,variantStage:'outfit-1'};
assert.equal(replacementForMissingPortrait(binding,npc,[base,variant])?.id,variant.id);
for(const extra of [{gender:'女'},{characterKey:'tianlong:other'},{faceFamilyKey:'face:other'},{id:'new@1:B2'},{ageRange:{min:50,max:60}},{portraitVerified:false}])assert.equal(replacementForMissingPortrait(binding,npc,[{...base,...extra}]),undefined);
assert.equal(replacementForMissingPortrait({...binding,characterKey:undefined},npc,[base]),undefined);
assert.equal(replacementForMissingPortrait(binding,npc,[base,{...base,id:'another@1:B1'}]),undefined);
assert.equal(replacementForMissingPortrait(binding,npc,[base,{...variant,ageRange:{min:50,max:60}}])?.id,base.id);
const ordinary={npcId:'n',assetId:'coc@1:old-face',baseAssetId:'coc@1:old-face'};
const converted={...base,id:'complete@1:P5000',characterKey:undefined,faceFamilyKey:undefined,legacyAssetIds:['coc@1:old-face']};
assert.equal(replacementForMissingPortrait(ordinary,npc,[converted])?.id,converted.id);
assert.equal(replacementForMissingPortrait(ordinary,npc,[converted,{...converted,id:'complete@1:P5001'}]),undefined);
assert.equal(replacementForMissingPortrait(ordinary,npc,[{...converted,gender:'女'}]),undefined);
const mappedBase={...base,id:'complete@1:P1',legacyAssetIds:['old@1:B1']};
const mappedVariant={...variant,id:'complete@1:P2',baseAssetId:mappedBase.id,legacyAssetIds:['old@1:V1']};
assert.equal(replacementForMissingPortrait(binding,npc,[mappedBase,mappedVariant])?.id,mappedVariant.id);
assert.equal(replacementForMissingPortrait(binding,npc,[{...mappedBase,legacyAssetIds:[]},mappedVariant]),undefined);
console.log('Missing portrait recovery: same logical base/key/family/gender/age/verified and unique base checked; ordinary identity never reassigned; incompatible variant falls back to same base.');`;
const result=await build({stdin:{contents:source,loader:'ts',resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',write:false,logLevel:'silent'});await import('data:text/javascript;base64,'+Buffer.from(result.outputFiles[0].text).toString('base64'));
